/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegoahorcado_labp2;

import javax.swing.JOptionPane;

/**
 *
 * @author Tommy Lee Pon
 */
public class Game_FORM extends javax.swing.JFrame {
    private JuegoAhorcadoBase juego;
    
    /**
     * Creates new form NewJFrame
     */
    public Game_FORM(String tipo) {
        if(tipo.equals("azar")){
            juego=new JugarAhorcadoAzar();
        } else {
            juego=new JugarAhorcadoFijo();
        }
        initComponents();
        progresoLabel.setText(juego.palabraActual.replace(' ', '-'));
        intentosLabel.setText(Integer.toString(juego.intentos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        progresoLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        guessInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intentosLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progresoLabel.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        progresoLabel.setForeground(new java.awt.Color(255, 255, 255));
        progresoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progresoLabel.setText("[WORD]");
        getContentPane().add(progresoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 200, 100));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegoahorcado_labp2/pizarra.jpg"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 15, 396, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));
        getContentPane().add(guessInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Guess:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Intentos: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        intentosLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        intentosLabel.setText("##");
        getContentPane().add(intentosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String letra=guessInput.getText();
        guessInput.setText("");
        if(letra.length()==1){
            if(juego.jugar(letra.charAt(0))){
                JOptionPane.showMessageDialog(this, "Has Ganado!");
                this.dispose();
                new Menu_FORM().setVisible(true);
            };
        }
        if(juego.intentos==0){
            JOptionPane.showMessageDialog(this, "Has perdido, la palabra era " + juego.palabraSecreta);
            this.dispose();
            new Menu_FORM().setVisible(true);
        }
        intentosLabel.setText(Integer.toString(juego.intentos));
        progresoLabel.setText(juego.palabraActual.replace(' ', '-'));
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_FORM(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessInput;
    private javax.swing.JLabel intentosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel progresoLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
